package CosasBD;
// Generated 6/06/2017 02:30:11 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;

/**
 * Actividad generated by hbm2java
 */
public class Actividad implements java.io.Serializable {

    private ActividadId id;
    private BigDecimal version;
    private String actividadNombre;
    private String prueba;
    private boolean selected;

    public boolean isSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
    }

    public Actividad() {
    }

    public Actividad(ActividadId id, String actividadNombre) {
        this.id = id;
        this.actividadNombre = actividadNombre;
    }

    public Actividad(ActividadId id, String actividadNombre, String prueba) {
        this.id = id;
        this.actividadNombre = actividadNombre;
        this.prueba = prueba;
    }

    public ActividadId getId() {
        return this.id;
    }

    public void setId(ActividadId id) {
        this.id = id;
    }

    public BigDecimal getVersion() {
        return this.version;
    }

    public void setVersion(BigDecimal version) {
        this.version = version;
    }

    public String getActividadNombre() {
        return this.actividadNombre;
    }

    public void setActividadNombre(String actividadNombre) {
        this.actividadNombre = actividadNombre;
    }

    public String getPrueba() {
        return this.prueba;
    }

    public void setPrueba(String prueba) {
        this.prueba = prueba;
    }
}
